/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as CashbookRouteImport } from './routes/cashbook'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as EmiRouteImport } from './routes/emi'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PosRouteImport } from './routes/pos'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as RepairsRouteImport } from './routes/repairs'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SuppliersRouteImport } from './routes/suppliers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbookRoute = CashbookRouteImport.update({
  id: '/cashbook',
  path: '/cashbook',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiRoute = EmiRouteImport.update({
  id: '/emi',
  path: '/emi',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsRoute = RepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/cashbook': typeof CashbookRoute
  '/customers': typeof CustomersRoute
  '/emi': typeof EmiRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/permissions': typeof PermissionsRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchase': typeof PurchaseRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/cashbook': typeof CashbookRoute
  '/customers': typeof CustomersRoute
  '/emi': typeof EmiRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/permissions': typeof PermissionsRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchase': typeof PurchaseRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/cashbook': typeof CashbookRoute
  '/customers': typeof CustomersRoute
  '/emi': typeof EmiRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/permissions': typeof PermissionsRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/purchase': typeof PurchaseRoute
  '/repairs': typeof RepairsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/suppliers': typeof SuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/cashbook'
    | '/customers'
    | '/emi'
    | '/employees'
    | '/expenses'
    | '/login'
    | '/orders'
    | '/payments'
    | '/payroll'
    | '/permissions'
    | '/pos'
    | '/products'
    | '/purchase'
    | '/repairs'
    | '/reports'
    | '/returns'
    | '/settings'
    | '/stock'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/cashbook'
    | '/customers'
    | '/emi'
    | '/employees'
    | '/expenses'
    | '/login'
    | '/orders'
    | '/payments'
    | '/payroll'
    | '/permissions'
    | '/pos'
    | '/products'
    | '/purchase'
    | '/repairs'
    | '/reports'
    | '/returns'
    | '/settings'
    | '/stock'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/cashbook'
    | '/customers'
    | '/emi'
    | '/employees'
    | '/expenses'
    | '/login'
    | '/orders'
    | '/payments'
    | '/payroll'
    | '/permissions'
    | '/pos'
    | '/products'
    | '/purchase'
    | '/repairs'
    | '/reports'
    | '/returns'
    | '/settings'
    | '/stock'
    | '/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  CashbookRoute: typeof CashbookRoute
  CustomersRoute: typeof CustomersRoute
  EmiRoute: typeof EmiRoute
  EmployeesRoute: typeof EmployeesRoute
  ExpensesRoute: typeof ExpensesRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PaymentsRoute: typeof PaymentsRoute
  PayrollRoute: typeof PayrollRoute
  PermissionsRoute: typeof PermissionsRoute
  PosRoute: typeof PosRoute
  ProductsRoute: typeof ProductsRoute
  PurchaseRoute: typeof PurchaseRoute
  RepairsRoute: typeof RepairsRoute
  ReportsRoute: typeof ReportsRoute
  ReturnsRoute: typeof ReturnsRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
  SuppliersRoute: typeof SuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbook': {
      id: '/cashbook'
      path: '/cashbook'
      fullPath: '/cashbook'
      preLoaderRoute: typeof CashbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi': {
      id: '/emi'
      path: '/emi'
      fullPath: '/emi'
      preLoaderRoute: typeof EmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs': {
      id: '/repairs'
      path: '/repairs'
      fullPath: '/repairs'
      preLoaderRoute: typeof RepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  CashbookRoute: CashbookRoute,
  CustomersRoute: CustomersRoute,
  EmiRoute: EmiRoute,
  EmployeesRoute: EmployeesRoute,
  ExpensesRoute: ExpensesRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PaymentsRoute: PaymentsRoute,
  PayrollRoute: PayrollRoute,
  PermissionsRoute: PermissionsRoute,
  PosRoute: PosRoute,
  ProductsRoute: ProductsRoute,
  PurchaseRoute: PurchaseRoute,
  RepairsRoute: RepairsRoute,
  ReportsRoute: ReportsRoute,
  ReturnsRoute: ReturnsRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
